spring:
  active: h2

logging:
  level:
    root: info
    org.springframework.boot: info
    com.hotstrip.linux.monitor: info

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html