server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:~/linux-monitor;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

database:
  dialect: h2
  init_script: "META-INF/schema.h2.sql"