spring:
  active: h2
  # thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    root: info
    org.springframework.boot: info
    com.hotstrip.linux.monitor: info
